"""add_parallel_date_fields_s9

Revision ID: 72a40fc53a29
Revises: 
Create Date: 2026-05-05 22:41:31.628687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a40fc53a29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'cbcq', 'ke_toan', 'gddh', name='roleenum'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workflow_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('ho_so_gpmb',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dia_chi', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('chuan_bi', 'thuc_hien', 'hoan_thanh', name='hosostatusenum'), nullable=False),
    sa.Column('cbcq_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('ngay_bat_dau', sa.Date(), nullable=True),
    sa.Column('ngay_ket_thuc', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cbcq_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id_model', 'notifications', ['user_id'], unique=False)
    op.create_table('workflow_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('planned_days', sa.Integer(), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('org_in_charge', sa.String(length=255), nullable=True),
    sa.Column('org_coordinate', sa.String(length=255), nullable=True),
    sa.Column('per_household', sa.Boolean(), nullable=False),
    sa.Column('is_parallel', sa.Boolean(), nullable=False),
    sa.Column('require_scan', sa.Boolean(), nullable=False),
    sa.Column('field_so_vb', sa.Boolean(), nullable=False),
    sa.Column('field_ngay_vb', sa.Boolean(), nullable=False),
    sa.Column('field_loai_vb', sa.Boolean(), nullable=False),
    sa.Column('field_gia_tri_trinh', sa.Boolean(), nullable=False),
    sa.Column('field_gia_tri_duyet', sa.Boolean(), nullable=False),
    sa.Column('field_ghi_chu', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['workflow_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ho',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ho_so_id', sa.UUID(), nullable=False),
    sa.Column('ma_ho', sa.String(length=50), nullable=False),
    sa.Column('ten_chu_ho', sa.Text(), nullable=False),
    sa.Column('dia_chi', sa.Text(), nullable=True),
    sa.Column('loai_dat', sa.String(length=50), nullable=True),
    sa.Column('thua', sa.String(length=100), nullable=True),
    sa.Column('dien_tich', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('moi', 'dang_xu_ly', 'da_thong_nhat', 'da_chi_tra', 'da_ban_giao', name='hostatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ho_so_id'], ['ho_so_gpmb.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ho_so_id', 'ma_ho', name='uq_ho_ho_so_ma')
    )
    op.create_index('ix_ho_ho_so_id', 'ho', ['ho_so_id'], unique=False)
    op.create_table('ho_so_workflow_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ho_so_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('planned_days', sa.Integer(), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('org_in_charge', sa.String(length=255), nullable=True),
    sa.Column('org_coordinate', sa.String(length=255), nullable=True),
    sa.Column('per_household', sa.Boolean(), nullable=False),
    sa.Column('is_parallel', sa.Boolean(), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('require_scan', sa.Boolean(), nullable=False),
    sa.Column('field_so_vb', sa.Boolean(), nullable=False),
    sa.Column('field_ngay_vb', sa.Boolean(), nullable=False),
    sa.Column('field_loai_vb', sa.Boolean(), nullable=False),
    sa.Column('field_gia_tri_trinh', sa.Boolean(), nullable=False),
    sa.Column('field_gia_tri_duyet', sa.Boolean(), nullable=False),
    sa.Column('field_ghi_chu', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ho_so_id'], ['ho_so_gpmb.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['ho_so_workflow_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['workflow_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ho_so_workflow_nodes_ho_so_id', 'ho_so_workflow_nodes', ['ho_so_id'], unique=False)
    op.create_index('ix_ho_so_workflow_nodes_parent_id', 'ho_so_workflow_nodes', ['parent_id'], unique=False)
    op.create_table('ke_hoach_thang',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ho_so_id', sa.UUID(), nullable=False),
    sa.Column('thang', sa.Integer(), nullable=False),
    sa.Column('nam', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('da_xuat_bao_cao', sa.Boolean(), nullable=False),
    sa.Column('ngay_xuat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ho_so_id'], ['ho_so_gpmb.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ho_so_id', 'thang', 'nam', name='uq_ke_hoach_thang')
    )
    op.create_table('workflow_node_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('ten_tai_lieu', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['workflow_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ho_so_chi_tra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ho_so_id', sa.UUID(), nullable=False),
    sa.Column('ho_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('da_tao', 'cho_phe_duyet', 'da_phe_duyet', 'bi_tu_choi', 'da_ban_giao', name='chitrastatusenum'), nullable=False),
    sa.Column('so_tien_bt', sa.Float(), nullable=True),
    sa.Column('so_tien_ht', sa.Float(), nullable=True),
    sa.Column('so_tien_tdc', sa.Float(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('ke_toan_id', sa.UUID(), nullable=True),
    sa.Column('gddh_id', sa.UUID(), nullable=True),
    sa.Column('ly_do_tu_choi', sa.Text(), nullable=True),
    sa.Column('ngay_gui_duyet', sa.DateTime(), nullable=True),
    sa.Column('ngay_duyet', sa.DateTime(), nullable=True),
    sa.Column('ngay_ban_giao_mat_bang', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gddh_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ho_id'], ['ho.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ho_so_id'], ['ho_so_gpmb.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ke_toan_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ho_so_chi_tra_ho_so_id', 'ho_so_chi_tra', ['ho_so_id'], unique=False)
    op.create_table('node_household_scope',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_node_id', sa.UUID(), nullable=False),
    sa.Column('ho_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ho_id'], ['ho.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['ho_so_workflow_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_node_id', 'ho_id', name='uq_node_household_scope')
    )
    op.create_table('task_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ho_so_id', sa.UUID(), nullable=False),
    sa.Column('workflow_node_id', sa.UUID(), nullable=False),
    sa.Column('ho_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('dang_thuc_hien', 'hoan_thanh', name='taskstatusenum'), nullable=False),
    sa.Column('so_vb', sa.String(length=100), nullable=True),
    sa.Column('ngay_vb', sa.DateTime(), nullable=True),
    sa.Column('loai_vb', sa.String(length=100), nullable=True),
    sa.Column('gia_tri_trinh', sa.Float(), nullable=True),
    sa.Column('gia_tri_duyet', sa.Float(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('scan_file_path', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ho_id'], ['ho.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ho_so_id'], ['ho_so_gpmb.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['ho_so_workflow_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_node_id', 'ho_id', name='uq_task_node_ho')
    )
    op.create_index('ix_task_instances_ho_id', 'task_instances', ['ho_id'], unique=False)
    op.create_index('ix_task_instances_ho_so_id', 'task_instances', ['ho_so_id'], unique=False)
    op.create_index('ix_task_instances_workflow_node_id', 'task_instances', ['workflow_node_id'], unique=False)
    op.create_index('uq_task_node_ho_null', 'task_instances', ['workflow_node_id'], unique=True, postgresql_where='ho_id IS NULL')
    op.create_table('ke_hoach_thang_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ke_hoach_thang_id', sa.UUID(), nullable=False),
    sa.Column('task_instance_id', sa.UUID(), nullable=True),
    sa.Column('ten_cong_viec', sa.Text(), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('ngay_du_kien', sa.Date(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('la_viec_phat_sinh', sa.Boolean(), nullable=False),
    sa.Column('da_hoan_thanh', sa.Boolean(), nullable=False),
    sa.Column('thu_tu', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ke_hoach_thang_id'], ['ke_hoach_thang.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_instance_id', sa.UUID(), nullable=False),
    sa.Column('ten_tai_lieu', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_attachments')
    op.drop_table('ke_hoach_thang_item')
    op.drop_index('uq_task_node_ho_null', table_name='task_instances', postgresql_where='ho_id IS NULL')
    op.drop_index('ix_task_instances_workflow_node_id', table_name='task_instances')
    op.drop_index('ix_task_instances_ho_so_id', table_name='task_instances')
    op.drop_index('ix_task_instances_ho_id', table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_table('node_household_scope')
    op.drop_index('ix_ho_so_chi_tra_ho_so_id', table_name='ho_so_chi_tra')
    op.drop_table('ho_so_chi_tra')
    op.drop_table('workflow_node_documents')
    op.drop_table('ke_hoach_thang')
    op.drop_index('ix_ho_so_workflow_nodes_parent_id', table_name='ho_so_workflow_nodes')
    op.drop_index('ix_ho_so_workflow_nodes_ho_so_id', table_name='ho_so_workflow_nodes')
    op.drop_table('ho_so_workflow_nodes')
    op.drop_index('ix_ho_ho_so_id', table_name='ho')
    op.drop_table('ho')
    op.drop_table('workflow_nodes')
    op.drop_index('ix_notifications_user_id_model', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('ho_so_gpmb')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('workflow_templates')
    op.drop_table('users')
    # ### end Alembic commands ###
